// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabalhoChamados.Models;

namespace TrabalhoChamados.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180913235423_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrabalhoChamados.Models.Chamados", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("data");

                    b.Property<DateTime>("datasolucao");

                    b.Property<string>("descricao");

                    b.Property<TimeSpan>("duracao");

                    b.Property<string>("email");

                    b.Property<TimeSpan>("horafinal");

                    b.Property<TimeSpan>("horainicio");

                    b.Property<string>("nomesolicitante");

                    b.Property<string>("numerochamado");

                    b.Property<string>("telefone");

                    b.HasKey("id");

                    b.ToTable("Chamados");
                });
#pragma warning restore 612, 618
        }
    }
}
