// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabalhoChamados.Models;

namespace TrabalhoChamados.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180926025754_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrabalhoChamados.Models.Chamado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("clienteid");

                    b.Property<DateTime>("data");

                    b.Property<DateTime>("datasolucao");

                    b.Property<string>("descricao");

                    b.Property<TimeSpan>("duracao");

                    b.Property<TimeSpan>("horafinal");

                    b.Property<TimeSpan>("horainicio");

                    b.Property<int?>("situacaoid");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.HasIndex("situacaoid");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("TrabalhoChamados.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("nomecliente");

                    b.Property<string>("telefone");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TrabalhoChamados.Models.Situacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("tiposituacao");

                    b.HasKey("id");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("TrabalhoChamados.Models.Chamado", b =>
                {
                    b.HasOne("TrabalhoChamados.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");

                    b.HasOne("TrabalhoChamados.Models.Situacao", "situacao")
                        .WithMany()
                        .HasForeignKey("situacaoid");
                });
#pragma warning restore 612, 618
        }
    }
}
